# Generated by Django 4.0 on 2023-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=1000)),
            ],
        ),
    ]
